# Generated by Django 6.0.6 on 2026-07-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0005_resumeshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('PORTFOLIO', 'Portfolio'), ('LEETCODE', 'LeetCode'), ('HACKERRANK', 'HackerRank'), ('CODECHEF', 'CodeChef'), ('OTHER', 'Other')], max_length=20)),
                ('profile_url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='ai_resume_building.candidate')),
            ],
            options={
                'db_table': 'social_link',
                'ordering': ['platform'],
            },
        ),
    ]
