# Generated by Django 6.0.6 on 2026-07-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0006_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='resumeshare',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='ResumeShare',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
