# Generated by Django 6.0.6 on 2026-07-07 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0007_remove_candidate_user_remove_certification_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='candidate/profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidate/resume/')),
                ('profile_summary', models.TextField(blank=True, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=150)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('current_location', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
    ]
