# Generated by Django 6.0.6 on 2026-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0008_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_otp',
            },
        ),
    ]
