# Generated by Django 6.0.6 on 2026-07-07 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'purpose'], name='otp_email_9bad1d_idx'),
        ),
    ]
