# Generated by Django 6.0.6 on 2026-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0012_alter_otp_options_alter_passwordresettoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
