# Generated by Django 6.0.6 on 2026-07-14 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0014_resume_resumeachievement_resumecertification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_job_title',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_summary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
