# Generated by Django 5.2.6 on 2026-07-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0016_recruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeSkill',
        ),
    ]
