# Generated by Django 5.2.6 on 2026-07-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0020_delete_resumecertification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeProject',
        ),
    ]
