# Generated by Django 5.2.6 on 2026-07-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0022_delete_resumeworkexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepersonalinformation',
            name='resume',
        ),
        migrations.DeleteModel(
            name='ResumeEducation',
        ),
        migrations.DeleteModel(
            name='ResumePersonalInformation',
        ),
    ]
