# Generated by Django 5.2.6 on 2026-07-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0023_remove_resumepersonalinformation_resume_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
