# Generated by Django 5.2.6 on 2026-07-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0026_candidatecertification_candidateeducation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
    ]
