# Generated by Django 5.2.6 on 2026-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0027_remove_candidate_email_remove_candidate_phone_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidatecertification',
            index=models.Index(fields=['candidate'], name='candidate_c_candida_2a9388_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecertification',
            index=models.Index(fields=['resume_version'], name='candidate_c_resume__507111_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecertification',
            index=models.Index(fields=['certificate_name'], name='candidate_c_certifi_3d9aca_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateeducation',
            index=models.Index(fields=['candidate'], name='candidate_e_candida_860457_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateeducation',
            index=models.Index(fields=['resume_version'], name='candidate_e_resume__76dc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateeducation',
            index=models.Index(fields=['degree'], name='candidate_e_degree_fad4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateexperience',
            index=models.Index(fields=['candidate'], name='candidate_e_candida_c3f673_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateexperience',
            index=models.Index(fields=['resume_version'], name='candidate_e_resume__899ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateexperience',
            index=models.Index(fields=['company_name'], name='candidate_e_company_e91cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatelanguage',
            index=models.Index(fields=['candidate'], name='candidate_l_candida_5c2bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatelanguage',
            index=models.Index(fields=['resume_version'], name='candidate_l_resume__8f856a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatelanguage',
            index=models.Index(fields=['language'], name='candidate_l_languag_256171_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['candidate'], name='candidate_s_candida_d42dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['resume_version'], name='candidate_s_resume__472072_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['skill_name'], name='candidate_s_skill_n_6cbf64_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeparseddata',
            index=models.Index(fields=['candidate'], name='resume_pars_candida_add481_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeparseddata',
            index=models.Index(fields=['candidate', 'is_active'], name='resume_pars_candida_d191f4_idx'),
        ),
    ]
