# Generated by Django 5.2.6 on 2026-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0028_candidatecertification_candidate_c_candida_2a9388_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='full_name',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
