# Generated by Django 5.2.6 on 2026-08-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume_building', '0029_remove_recruiter_full_name_recruiter_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
